#!/bin/bash
# Prejdi do priečinka s .ino súborom
cd ~/catkin_ws/src/jetbot_pro/arduino/ultrasonic

# Skompiluj a nahraj
arduino-cli compile --fqbn arduino:avr:nano:cpu=atmega328old
arduino-cli upload --fqbn arduino:avr:nano:cpu=atmega328old -p /dev/ttyUSB0
